import type { GenerationTask } from "./types";

const now = Date.now();

export const generationTaskSeed: GenerationTask[] = [
  {
    id: "task-cyberpunk-city",
    type: "image",
    prompt: "Неоновый киберпанк-город под дождём, вид сверху",
    model: "Midjourney v6",
    status: "running",
    progress: 64,
    createdAt: now - 8 * 60_000,
    credits: 80,
    estimatedMs: 30_000,
  },
  {
    id: "task-mountain-lake",
    type: "video",
    prompt: "Дрон-облёт горного озера на рассвете, 5 сек",
    model: "Kling 3.0",
    status: "running",
    progress: 28,
    createdAt: now - 7 * 60_000,
    credits: 150,
    estimatedMs: 120_000,
  },
  {
    id: "task-coffee-script",
    type: "text",
    prompt: "Сценарий рекламного ролика для кофейни, 30 секунд",
    model: "GPT-4o",
    status: "queued",
    progress: 0,
    createdAt: now - 6 * 60_000,
    credits: 6,
    estimatedMs: 8_000,
  },
  {
    id: "task-logo",
    type: "image",
    prompt: "Минималистичный логотип кофейни, бежевые тона",
    model: "Flux",
    status: "done",
    progress: 100,
    createdAt: now - 5 * 60_000,
    completedAt: now - 90_000,
    credits: 80,
    estimatedMs: 25_000,
  },
  {
    id: "task-voice",
    type: "audio",
    prompt: "Озвучка приветствия мужским голосом",
    model: "ElevenLabs",
    status: "failed",
    progress: 18,
    createdAt: now - 4 * 60_000,
    credits: 40,
    estimatedMs: 45_000,
    error: "Недостаточно кредитов",
  },
  {
    id: "task-retro-poster",
    type: "image",
    prompt: "Постер в стиле ретро-футуризм 80-х",
    model: "Seedream",
    status: "canceled",
    progress: 12,
    createdAt: now - 3 * 60_000,
    credits: 80,
    estimatedMs: 30_000,
    error: "Отменено пользователем",
  },
  {
    id: "task-product-copy",
    type: "text",
    prompt: "Короткое описание подписки ERA2 для лендинга",
    model: "Claude Sonnet",
    status: "queued",
    progress: 0,
    createdAt: now - 2 * 60_000,
    credits: 8,
    estimatedMs: 10_000,
  },
  {
    id: "task-avatar",
    type: "image",
    prompt: "Аватар ассистента в фирменном стиле warm coal",
    model: "Flux Pro",
    status: "queued",
    progress: 0,
    createdAt: now - 90_000,
    credits: 90,
    estimatedMs: 35_000,
  },
  {
    id: "task-jingle",
    type: "audio",
    prompt: "Короткий аудио-джингл для старта генерации",
    model: "Suno",
    status: "done",
    progress: 100,
    createdAt: now - 12 * 60_000,
    completedAt: now - 10 * 60_000,
    credits: 55,
    estimatedMs: 60_000,
  },
  {
    id: "task-storyboard",
    type: "video",
    prompt: "Сториборд вертикального видео для нового тарифа",
    model: "Runway",
    status: "queued",
    progress: 0,
    createdAt: now - 30_000,
    credits: 170,
    estimatedMs: 140_000,
  },
];
